CC=gcc
CFLAGS=-Wall -pedantic

all: server client util ... (list all executables)

server: server.c util.c ...
        $(CC) $(CFLAGS) -o server server.c util.c ...

client: client.c ...
        $(CC) $(CFLAGS) -o client client.c ...

util: util.c ...
        $(CC) $(CFLAGS) -o util util.c ...

clean:
        rm -f *~ *.o server client util ... (list all executables)